---

- hosts: all
  become: true
  tasks:
  
#Ubuntu and CentOS

  - name: install apache and php package 
    package: #whatever target below uses (apt/yum/dnf)
      name: 
        - "{{ apache_package }}"
        - "{{ php_package }}"
      state: latest
      update_cache: yes
    
    
    